personal_use_script = "x"
secret = "x"
user_agent = "x"
username = "x"
password = "x"

INITIAL_COUNT_VAL = 0
coin_dictionary = {
    ("bitcoin", "btc", "xbt") : INITIAL_COUNT_VAL,
    ("ethereum", "eth") : INITIAL_COUNT_VAL,
    ("binance coin", "bnb") : INITIAL_COUNT_VAL,
    ("tether", "usdt") : INITIAL_COUNT_VAL,
    ("cardano", "ada") : INITIAL_COUNT_VAL,
    ("polkadot", "dot") : INITIAL_COUNT_VAL,
    ("ripple", "xrp") : INITIAL_COUNT_VAL,
    ("uniswap", "uniswap") : INITIAL_COUNT_VAL,
    ("litecoin", "ltc") : INITIAL_COUNT_VAL,
    ("chainlink", "link") : INITIAL_COUNT_VAL,
    ("bitcoin cash", "bch") : INITIAL_COUNT_VAL,
    ("stellar", "lumens", "xlm") : INITIAL_COUNT_VAL,
    ("usd coin", "usdc") : INITIAL_COUNT_VAL,
    ("dogecoin", "doge") : INITIAL_COUNT_VAL,
    ("wrapped bitcoin", "wbtc") : INITIAL_COUNT_VAL,
    ("aave", "aave") : INITIAL_COUNT_VAL,
    ("theta", "theta") : INITIAL_COUNT_VAL,
    ("cosmos", "atom") : INITIAL_COUNT_VAL,
    ("crypto.com coin", "cro") : INITIAL_COUNT_VAL,
    ("monero", "xmr") : INITIAL_COUNT_VAL,
    ("vechain", "vet") : INITIAL_COUNT_VAL,
    ("tron", "trx") : INITIAL_COUNT_VAL,
    ("oita", "moita") : INITIAL_COUNT_VAL,
    ("solana", "solana") : INITIAL_COUNT_VAL,
    ("eos", "eos") : INITIAL_COUNT_VAL,
    ("gitcoin sv", "bsv") : INITIAL_COUNT_VAL,
    ("terra", "luna") : INITIAL_COUNT_VAL,
    ("tezos", "xtz") : INITIAL_COUNT_VAL,
    ("binance usd", "busd") : INITIAL_COUNT_VAL,
    ("huobi", "huobi") : INITIAL_COUNT_VAL,
    ("ftx token", "ftt") : INITIAL_COUNT_VAL,
    ("neo", "neo") : INITIAL_COUNT_VAL,
    ("dai", "dai") : INITIAL_COUNT_VAL,
    ("elrond", "egld") : INITIAL_COUNT_VAL,
    ("synthetix", "snx") : INITIAL_COUNT_VAL,
    ("algorand", "algo") : INITIAL_COUNT_VAL,
    ("filecoin", "fil") : INITIAL_COUNT_VAL,
    ("the graph", "grt") : INITIAL_COUNT_VAL,
    ("compound", "compound") : INITIAL_COUNT_VAL,
    ("sushiswap", "sushi") : INITIAL_COUNT_VAL,
    ("maker", "mkr") : INITIAL_COUNT_VAL,
    ("avalance", "avax") : INITIAL_COUNT_VAL,
    ("dash", "dash") : INITIAL_COUNT_VAL,
    ("kusama", "ksm") : INITIAL_COUNT_VAL,
    ("decred", "dcr") : INITIAL_COUNT_VAL,
    ("unus sed leo", "leo") : INITIAL_COUNT_VAL,
    ("pancakeswap", "cake") : INITIAL_COUNT_VAL,
    ("zcash", "zec") : INITIAL_COUNT_VAL,
    ("yearn.fiance", "yearn", "yfi") : INITIAL_COUNT_VAL
}