# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run the script
      env: # environment variables
        personal_use_script: ${{ secrets.personal_use_script }}
        secret: ${{ secrets.secret }}
        user_agent: ${{ secrets.user_agent }}
        reddit_py_username: ${{ secrets.reddit_py_username }}
        password: ${{ secrets.password }}
        coinmarketcap_api_key: ${{ secrets.coinmarketcap_api_key }}
      run: |
        python -m nltk.downloader stopwords
        python main.py
          
